# TEST CASES GENERATED BY CHAT GPT

import unittest
from HeapSort import heapSort

class TestHeapSort(unittest.TestCase):

    def setUp(self):
        print("\nRunning test case...")

    def test_sorted_array(self):
        arr = [1, 2, 3, 4, 5]
        expected = [1, 2, 3, 4, 5]
        heapSort(arr)
        self.assertEqual(arr, expected)
        print("Test sorted array passed.")

    def test_reverse_sorted_array(self):
        arr = [5, 4, 3, 2, 1]
        expected = [1, 2, 3, 4, 5]
        heapSort(arr)
        self.assertEqual(arr, expected)
        print("Test reverse sorted array passed.")

    def test_random_array(self):
        arr = [12, 11, 13, 5, 6, 7]
        expected = [5, 6, 7, 11, 12, 13]
        heapSort(arr)
        self.assertEqual(arr, expected)
        print("Test random array passed.")

    def test_single_element(self):
        arr = [1]
        expected = [1]
        heapSort(arr)
        self.assertEqual(arr, expected)
        print("Test single element passed.")

    def test_all_same_elements(self):
        arr = [4, 4, 4, 4, 4]
        expected = [4, 4, 4, 4, 4]
        heapSort(arr)
        self.assertEqual(arr, expected)
        print("Test all same elements passed.")

    def test_negative_elements(self):
        arr = [-1, -3, -2, -5, -4]
        expected = [-5, -4, -3, -2, -1]
        heapSort(arr)
        self.assertEqual(arr, expected)
        print("Test negative elements passed.")

    def test_mixed_elements(self):
        arr = [3, -2, 5, 1, 0, -4]
        expected = [-4, -2, 0, 1, 3, 5]
        heapSort(arr)
        self.assertEqual(arr, expected)
        print("Test mixed elements passed.")

    def test_large_numbers(self):
        arr = [100000, 99999, 100001]
        expected = [99999, 100000, 100001]
        heapSort(arr)
        self.assertEqual(arr, expected)
        print("Test large numbers passed.")

    def tearDown(self):
        print("Test case completed.\n")


if __name__ == '__main__':
    test_suite = unittest.TestLoader().loadTestsFromTestCase(TestHeapSort)
    result = unittest.TextTestRunner(verbosity=2).run(test_suite)
    
    total_tests = result.testsRun
    failures = len(result.failures)
    passes = total_tests - failures
    
    print(f"\nTotal tests run: {total_tests}")
    print(f"Total passed: {passes}")
    print(f"Total failed: {failures}")
    print("Test case run completed.")
